package com.pfseven.smdb.smdb.domain;

public enum Genre {

    COMEDY, ACTION, FANTASY,
    HORROR, MYSTERY, MUSIC, ROMANCE,
    THRILLER, WESTERN, ANIMATION,
    SUPERHERO, DOCUMENTARY, BIOGRAPHY,
    ADVENTURE, SCI_FI, DRAMA, SHORT,
    MUSICAL, SITCOM, REALITY, HISTORY,
    WAR, SPORT, FAMILY, CRIME, OTHER

}
